apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  labels:
    app: telegraf
spec:
  ports:
    - port: 8125
      targetPort: 8125
      protocol: TCP
  type: ClusterIP
  selector:
    app: telegraf
