resources:
  - ./aws.cert-manager.yaml
  - ./elasticsearch.default.yaml
  - ./elasticsearch.monitors.yaml
  - ./minio-console.minio.yaml
  - ./minio.default.yaml
  - ./minio.spark.yaml
  - ./mongodb.default.yaml
  - ./mongodb.mongodb.yaml
  - ./registry.registry.yaml
