apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: clever.minio.secrets
