apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_USERNAME
      remoteRef:
        key: clever.mongodb.secrets
        property: MONGODB_USERNAME
    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: clever.mongodb.secrets
        property: MONGODB_PASSWORD
    - secretKey: MONGODB_ADMIN_PASSWORD
      remoteRef:
        key: clever.mongodb.secrets
        property: MONGODB_PASSWORD
