apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
  criSocket: /var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  taints: []
certificateKey: 0faec066c7b58657b6e9879c79d32b7ab1e7208a3c93dff6f6de0b4b4412d5ff
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: "aws"
  timeoutForControlPlane: 4m0s
  certSANs:
    - "ec2-52-78-251-181.ap-northeast-2.compute.amazonaws.com"
    - "ec2-52-78-197-96.ap-northeast-2.compute.amazonaws.com"
    - "ec2-3-39-105-105.ap-northeast-2.compute.amazonaws.com"
certificatesDir: /etc/kubernetes/pki
clusterName: clever-vsup
controllerManager:
  extraArgs:
    cloud-provider: aws
    configure-cloud-routes: "false"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
#imageRepository: k8s.gcr.io
kubernetesVersion: 1.25.0
controlPlaneEndpoint: 52.78.251.181:6443
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
scheduler: {}
