apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 52.78.251.181:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abcdef.0123456789abcdef
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    cloud-provider: aws
caCertPath: /etc/kubernetes/pki/ca.crt
