apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
  name: node-exporter-svc
spec:
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  type: ClusterIP
  selector:
    app: node-exporter