apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-http
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus
