apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  annotations:
    pv.beta.kubernetes.io/gid: "2000"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"