apiVersion: 1
datasources:
  - name: Metrics
    type: prometheus
    access: proxy
    url: http://prometheus-service.monitors.svc.cluster.local:9090

  - name: InfluxDB_v2
    type: influxdb
    access: proxy
    url: http://influxdb-service.influxdb.svc:8086
    jsonData:
      version: Flux
      organization: "$INFLUXDB_ORG"
      defaultBucket: "$INFLUXDB_DB"
      tlsSkipVerify: true
    secureJsonData:
      token: "$INFLUXDB_TOKEN"
