apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      data:
        INFLUXDB_DB: "{{ .database | toString }}"
        INFLUXDB_URL: http://influxdb-service.influxdb.svc:8086
        INFLUXDB_TOKEN: "{{ .token | toString }}"
        INFLUXDB_USER: "{{ .username | toString }}"
        INFLUXDB_ORG: "{{ .org | toString }}"
  data:
    - secretKey: database
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_DATABASE
    - secretKey: username
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_USERNAME
    - secretKey: token
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_TOKEN
    - secretKey: org
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_ORG
