apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-creds
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: influxdb-creds
    creationPolicy: Owner
    template:
      data:
        INFLUXDB_DATABASE: "{{ .database | toString }}"
        INFLUXDB_USERNAME: "{{ .username | toString }}"
        INFLUXDB_PASSWORD: "{{ .password | toString }}"
        INFLUXDB_HOST: "{{ .host | toString }}"
  data:
    - secretKey: database
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_DATABASE
    - secretKey: username
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_USERNAME
    - secretKey: password
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_PASSWORD
    - secretKey: host
      remoteRef:
        key: cmonki.influxdb.secrets
        property: INFLUXDB_HOST
