apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
  namespace: istio-system
spec:
  dnsNames:
    - airflow.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: airflow-cert
