apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cvfilemanager-cert
  namespace: istio-system
spec:
  dnsNames:
    - file.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: cvfilemanager-cert
