apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dent-intro-cert
  namespace: istio-system
spec:
  dnsNames:
    - intro.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: dent-intro-cert
