apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
  namespace: istio-system
spec:
  dnsNames:
    - jenkins.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: jenkins-cert
