apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: istio-system
spec:
  dnsNames:
    - minio.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: minio-cert
