apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: object-storage-api-cert
  namespace: istio-system
spec:
  dnsNames:
    - cvobject.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: object-storage-api-cert
