apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: statistics-cert
  namespace: istio-system
spec:
  dnsNames:
    - statistics.clever2-test.vsmart00.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: statistics-cert
